version: '3.2'
services:
  composer:
    image: composer:2.0
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never
  php:
    image: php:8.0-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
  phpunit:
    image: php:8.0-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    